image:
  file: .gitpod.Dockerfile
tasks:
    - name: shop
      command: |
        sudo -s
        poetry shell
        poetry run threebot start --no-cert --background
ports:
  - port: 80
    onOpen: open-browser
  - port: 443
    onOpen: open-browser
