image:
  file: .gitpod.Dockerfile
tasks:
    - name: shop
      command: |
      cd /home/gitpod/code/tftshop
      poetry run threebot start --no-cert --local
ports:
  - port: 8080
    onOpen: open-browser
  - port: 8443
    onOpen: open-browser
