image:
  file: .gitpod.Dockerfile
tasks:
    - name: shop
      command: |
        cd /home/gitpod/code/tftshop
        electrum daemon -d --testnet
        poetry run threebot start --local --no-cert
ports:
  - port: 8080
    onOpen: open-browser
  - port: 8443
    onOpen: open-browser
